# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/estal/OneDrive/Documentos/Documents_2022_04_03/VHDL_course_2/uart_tx/ZYBO_Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_uart_tx_0_0_1/design_1_uart_tx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_uart_tx_0_0 || ORIG_REF_NAME==design_1_uart_tx_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0_1/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fsm_commands_at_0_1/design_1_fsm_commands_at_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fsm_commands_at_0_1 || ORIG_REF_NAME==design_1_fsm_commands_at_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_div_freq_0_0/design_1_div_freq_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_div_freq_0_0 || ORIG_REF_NAME==design_1_div_freq_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
